# -*- coding: utf-8 -*-
"""news_fetcher_SD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrpLnkDus1xW9ttX6u6xMCSHHe9P2X36

installation
"""

!pip install -q -U requests chromadb

"""import required libraries"""

import requests
import chromadb

"""news pipeline"""

class NewsPipeline:
    def __init__(self, api_key: str, collection_name: str = "news_collection"):
        self.api_key = api_key
        self.api_url = "https://newsdata.io/api/1/news"
        self.db_client = chromadb.Client()
        self.collection = self.db_client.get_or_create_collection(name=collection_name)

    def fetch_articles(self, limit: int = 5) -> list:
        params = {'apikey': self.api_key, 'language': 'en'}
        response = requests.get(self.api_url, params=params)
        if response.status_code == 200:
            return response.json().get('results', [])[:limit]
        return []

    def store_articles(self, articles: list) -> None:
        if not articles:
            return

        documents, metadatas, ids = [], [], []

        for index, item in enumerate(articles):
            title = item.get('title', 'N/A')
            description = item.get('description') or item.get('content') or ''
            pub_date = item.get('pubDate', 'N/A')
            creators = item.get('creator')
            author = ", ".join(creators) if isinstance(creators, list) else 'N/A'

            documents.append(f"{title}\n{description}")
            metadatas.append({"title": title, "author": author, "date": pub_date})
            ids.append(str(item.get('article_id', f"news_id_{index}")))

        self.collection.add(documents=documents, metadatas=metadatas, ids=ids)

    def get_stored_news(self):
        return self.collection.get()

if __name__ == "__main__":
    pipeline = NewsPipeline(api_key="YOUR_NEWSDATA_API_KEY")
    latest_news = pipeline.fetch_articles(limit=5)
    pipeline.store_articles(latest_news)
    stored_data = pipeline.get_stored_news()